name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - dask
  - netCDF4
  - bottleneck
  - scipy
  - pip
  - pip:
      - miepython
      - statsmodels
      - seaborn
      - plotnine
      - pre-commit
      - flask
      - gunicorn
      - requests
      - flask-cors
      - bump2version
prefix: /opt/conda
