name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - python-dotenv
    - streamlit
    - pandas
    - dask[complete]
    - matplotlib
    - miepython
    - netCDF4
    - scipy
    - seaborn
    - xarray
    - plotnine
    - statsmodels
    - pytest
    - tqdm
    - pyyaml
    - bump2version
    - plotly
prefix: /opt/conda
